version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    depends_on:
      - db
    links:
      - "db"
  frontend:
    build: ./frontend
    ports: 
      - "80:80"
    environment:
      NODE_ENV: production
